language: node_js
node_js:
- 8.11.1
sudo: required
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_92c453e01dfa_key -iv $encrypted_92c453e01dfa_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- sudo apt-get install -y sshpass

after_success:
- export SSHPASS=$DEPLOY_PASS
- sshpass -e ssh -o stricthostkeychecking=no $DEPLOY_USER@172.19.215.218 ./build.sh
addons:
  ssh_known_hosts: 172.19.215.218
branches:
  only:
  - master
