language: node_js
node_js:
- 8.11.1
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_92c453e01dfa_key -iv $encrypted_92c453e01dfa_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
after_success:
- export SSHPASS=$DEPLOY_PASS
- sshpass -e ssh -o stricthostkeychecking=no $DEPLOY_USER@101.132.179.88 "./build.sh"
addons:
  ssh_known_hosts: 101.132.179.88
branches:
  only:
  - master
env:
  global:
  - secure: Wp3pvJ5XtkkRV0GPB58fPLrytTHQ8OBqEB6tD0qFrU61Yrj9y/izLsKpT4ZSSnFAzT+LD6LK85MJLU0lQrWpKbHZQjwP9Wim+DZ7oteymfVU6aJoNdsDqXAbS2TyRPyTfAr7PwF0SrowynBDRSG5Elg0B57ljKZLBvwNHg8olANp7YZibbtEpFe6LaNSMvx2UEne4/Qa0ZAl+ItLA4ST17lvO5I3Ff9P6xDEDVV1+wqroS5uR4LA7oeDaRowOPftmprDfUT2McADa8dikI83nmOnHatcUmx2cAKl0tFa6iykm1OuIo4g/Ccb8OWSCuQtCCtPKMykmnk57dxNB5qtQD5NzzmyLaGUw7lKtNlN69CqIVVuzrG9Fb6tuJAUVfQr+cnuu7Pshp4HVQ63NB664I6oa879Kh835CrGRSMZF4vNUlcc3VLLdpiBSuucNWyaObubUY5Xb3TrRCP5Fzsm9hSGbyF+hudpd7Jz43dvVBOYgcbLO3qhBonOCdMGirVyTgRMPE8oPvByEpTo3WgNLTH0X7NGGlzTKzQjiUJLiz00q3D6QgD6ku2YNA8Iq+20fQKkGeddAwYezCnsJ/KNyFoodkBbq9VcYsAGJVd9xt9k4hxm6z1rWa9HIQD6xaVhbaJVRV6DiLX7brHBe0hJVrphaiumqGIOOtJd8mayVLU=
  - secure: HuYO7WuMd/gCFPWIpC/mWfpBHtRhFs82wWsEwkdNk4jNJFAbZ3qqHiJKYeRH8tbl5LUIN96haUN8NcVEtBrlYTrwvWHHkiciruxVaox7jClJxPjJp2mfj/FCOMQzlJvah7bupCZmPI7T/g2fA+VHa2ICKFCKWpKO4FZKj6AzlH9iQuoMAj+1oM2RktfEvQN401b4FPKvxHG7QmQkWpWOEjzrdFQF2LK2EGwr5+XGHXIudQH5lrllvoA6Ps0dO+hKRNLz6bnfqJEpD0ZZatCwVyEI+X8wM0tZosMDvH/PQL3+E23UOrTYQg7D+0fE6OsDt9I6aArXqrIWAFHb2CQTWlzfYcWjN7aLTmS8vVllYLfAK1+uxhX0Jzr2cJAKCeBr3S4S6X2QdaYLM1mZMwXcXxzosGDzeWA0WosEFziy5O/SvhvONjlJ4Xjfqc+SAnO+TXhR1iBUNO/oBZshJTgkKkVbUtJSXt94Pg2B/cPFyOgH+fwon8RYc3tEtD67aGwvfM9hkyR4gdRyv8o89UJwTcGArp9p1ysLaxJIE8kTylaU7v85oEw/CdRlhBmkROSBvhRwPbr9rKw028GFZ9Ueuo3DwzdSLqtAthFmEEt3hNK+0cP/WWF/oZdg6H8vnvfABz3o+xAJQzd+3Rsb6K/q/OyIxmiRNw4XeHoVrMFAtU4=
