language: node_js
node_js:
- 8.11.1
sudo: required
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_92c453e01dfa_key -iv $encrypted_92c453e01dfa_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- sudo apt-get install -y sshpass

after_success:
- export SSHPASS=$DEPLOY_PASS
- sshpass -e ssh -o stricthostkeychecking=no $DEPLOY_USER@101.132.179.88 ./build.sh
addons:
  ssh_known_hosts: 101.132.179.88
branches:
  only:
  - master
env:
  global:
  - secure: MccdnlE5wbpJ+O4qxZeLNyRMoWsQWeOPXXXoHiMZeV6y5xM+5pTAYyPD3oqlKDvXl2M0mK6x5OEkhEmbgxMFgXTKBaGeHOaaZSLmtWvU6GQCE0Xq++V5vutZiI3RITOQJwPEwvV13sojImuaobOkrgbV15AG4TKRem4Qp9bs52AnlF2zaADhhsT2NwTkIzOcuG3nCrxbJYrDnvR37jQjMrGta/d0MeMUpEFEL25kqNBcTGe1XAv+52DoqkRyAyrTATjs4f/qaV+P/j/5Xt334IAC6mFO6BwUuwLmFFYo8KWjeDvjNm84jxLwHlMZ4Wg/HxKTFn1VRfFa1weuw63x+iwSkZ8AvQ50IueZJ4RQaqy8F4LIZWHe8uyGwj3rUvnbq2HQZwWsFpLunC5bQIOLJaQbavt4dCc8DddPLsO4oSbxpylv/ZcMqIfs3z3QEKm9nEmJn98XOsgjoligVehkBMLGKsCW8jIFfrc8xRCwtgiK5cm/psrebZLfUl/IuALm1eoOoDbgBSOBEZpHjKmFarLsKdlprP+vmNnWiNPxyaMiaGVDv21RKn1cI56PbkAfnFGihizdtWnYBLbdG75fCFBWwDHzJwFYoFq1DZoNJVSk0GOZCKYlrYQjbtsqi/1q+AqOodnPfdg3qUTfMOEl+3P9RXkAQVi/EZGBvtn0AcE=
  - secure: VBGE3ALmXYKR6advTE0PGbAyZouFA6zE9XVMl5wHhDYCYa2MeqpatGc/lk/czB1ACZD8T8aoO2VLxmJb9MnBmefvRjUEiY/2gFNBLOYfDk0MnImQLNQ9eyELyYQgKqZQpupbVuy2gWypd9nsvA9IVluMHu009l5x0BqAfYG3/o3ybYhIklSZK+jBhk3ZgPGiHq8zDgl+YyXCLd3wxlOTa/2Fwcbr2IveR+hKr2bFQ7oMv0NWL2/tyo6nqv4ciZzFRxKzY2EFXkdeeR7cNRSIUCVG/cafSW/2GVzXeXITXJVaegKUdQhMnS+Y5uFIvskJXXyTGMbLYBu1zMeqKxQvvFPzsXx8KLGSIelyyfmyQzndBpFPPG5EnZZQLTT2/WjZ08a5AtlTbz17N24vnislKUx0eq3xeZDRXI9ts9pLFL4EBVllEHQhVmkAgbHSZbGqCDeZhT5vO7JBCri0NOa2VOy1wXicI0twMJlvJRD6W6rPXwgBKyEMCUb7bWYRxyzCuIK2PhrNJl29DDgPKdrNU8xyDvifUjpqQlDlDAMFl/32oPz6Gf2GOLi1Pp0sPR6xoVjvl2TMgWgh23eRgJOa3Curj1ZCQKh5MGFIHqz03aMTlX2c3Zy3Hk6kmhRfQHNTwzIXalK5pm4Ca8o2JFkahjDRrfZ57sn9mKHOUWMuA9g=
