language: node_js
node_js:
- 8.11.1
sudo: required
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_92c453e01dfa_key -iv $encrypted_92c453e01dfa_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- sudo apt-get install -y sshpass

script:
 - echo $PATH
 - npm run build

after_success:
- export SSHPASS=$DEPLOY_PASS
- sshpass -e ssh -o stricthostkeychecking=no root@101.132.179.88 "bash /usr/blog/blog-frontent-vue3.0/build.sh"
addons:
  ssh_known_hosts: 101.132.179.88
branches:
  only:
  - master
